version: "3.9"
services:
  articles_api:
    environment:
      - MONGO_HOST=mongo
      - MONGO_DB=savemyeyes
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1
    build: "backend"
    ports:
      - "5000:5000"
    depends_on:
      - "rabbitmq"
      - "mongo"
  model:
    environment:
      - RABBITMQ_HOST=rabbitmq
    build: "model"
    volumes:
      - ./model/modelSentiment:/opt/modelSentiment
    depends_on:
      - "articles_api"
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "5672:5672"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
